---
- name: Create nf.conf for loading the nf_conntrack module
  copy:
    src: net-modules.conf
    dest: /etc/modules-load.d/net-modules.conf

- name: Restart systemd-modules-load service
  service:
    name: systemd-modules-load
    enabled: yes
    state: restarted
