---
- name: Get os_version from /etc/os-release
  raw: "grep '^VERSION_ID=' /etc/os-release | sed s'/VERSION_ID=//'"
  register: os_version
  always_run: yes

- name: Get distro name from /etc/os-release
  raw: "grep '^NAME=' /etc/os-release | sed s'/NAME=//'"
  register: distro
  always_run: yes

- name: Determine if Atomic
  stat: path=/run/ostree-booted
  register: s
  changed_when: false

- name: Set the is_atomic fact
  set_fact:
    is_atomic: true
  when: s.stat.exists

- name: Stop firewalld service
  service:
    name: firewalld
    state: stopped

- name: Remove firewalld package
  action: "{{ ansible_pkg_mgr }}"
  args:
    name: "{{ item }}"
    state: absent
  with_items:
   - firewalld
   - iptables-services

- name: Upgrade all packages
  action: "{{ ansible_pkg_mgr }}"
  args:
    name: '*'
    state: latest

- name: Install basic packages
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
   - socat
   - htop
   - iotop
   - vim
   - git
   - ethtool
   - bridge-utils

- include: fedora-dnf.yml
  when: os_version.stdout|int >= 22 and 'Fedora' in distro.stdout and is_atomic is not defined

# Add "missing" nf* module to the kernel module loading
- include: kernel-module.yml
