---
- name: Install flannel
  action: "{{ ansible_pkg_mgr }}"
  args:
        name: flannel
        state: latest
  when: not is_atomic

- name: Install Flannel config file
  template: src=flanneld.j2 dest=/etc/sysconfig/flanneld
  notify:
    - restart flannel

- name: flannel version
  set_fact:
    flannel_version: "0.5.5"

- name: Create download dir
  file: path="/tmp/.ansible/files" state=directory

- name: Download tar file
  get_url:
    url: "https://github.com/coreos/flannel/releases/download/v{{ flannel_version }}/flannel-{{ flannel_version }}-linux-amd64.tar.gz"
    dest: /tmp/.ansible/files
    validate_certs: False
  environment:
    http_proxy: "{{ http_proxy|default('') }}"
    https_proxy: "{{ https_proxy|default('') }}"

- name: Extract tar file
  unarchive:
    src: "/tmp/.ansible/files/flannel-{{ flannel_version }}-linux-amd64.tar.gz"
    dest: /tmp/.ansible/files
    copy: no

- name: Copy flannel binary
  copy:
    src: /tmp/.ansible/files/flannel-{{ flannel_version }}/flanneld
    dest: /usr/bin/flanneld
    mode: 0755

- name: Copy flannel mk-docker-opts.sh
  copy:
    src: /tmp/.ansible/files/flannel-{{ flannel_version }}/mk-docker-opts.sh
    dest: /usr/libexec/flannel/mk-docker-opts.sh
    mode: 0755

- name: Launch Flannel
  service: name=flanneld state=started enabled=yes
  notify:
    - restart flannel
