version: "3.5"

services:
  mysql:
    image: docker.io/library/mysql:latest
    environment:
      DB_NAME: wordpress
      DB_USER: wordpress
      DB_PASS: wordpress
    volumes:
      - "mysql:/var/lib/mysql:rw"
  wordpress:
    image: docker.io/library/wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_AUTH_KEY: SECURE_AUTH_KEY
      WORDPRESS_LOGGED_IN_KEY: SECURE_LOGGED_IN_KEY
      WORDPRESS_AUTH_SALT: SECURE_AUTH_SALT
      WORDPRESS_LOGGED_IN_SALT: SECURE_LOGGED_IN_SALT
    volumes:
      - wordpress:/var/www/html
  phpmyadmin:
    image: docker.io/phpmyadmin/phpmyadmin
    ports:
      - 8181:80
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: workshop

volumes:
  mysql:
  wordpress:
