---
- name: Remove firewalld package
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
   - firewalld
   - iptables-services

- name: Upgrade all packages
  yum:
    name: '*'
    state: latest

- name: Install basic packages
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
   - socat
   - htop
   - iotop
   - vim
   - git
   - ethtool
   - bridge-utils

- include: hosts.yml
