# Kubernetes API version
apiVersion: v1
# Type of "request"
kind: Pod
# Metadata of the "object"
metadata:
  # Name of the "object"
  name: wordpress
  # Labels of the "object"
  labels:
    # A lable named "name" with value "wordpress"
    name: wordpress
# spec ~= Specificationsof the "object"
spec:
  # List of Container definitions
  containers:
    # The "name"/"suffix" of the container name
    - name: phpmyadmin
      # What Docker image to use
      image: corbinu/docker-phpmyadmin
      env:
        - name: MYSQL_USERNAME
          value: root
        - name: MYSQL_ROOT_PASSWORD
          value: wordpress
      # List of container ports reachable from within the cluster
      ports:
        - containerPort: 80
          name: phpmyadmin
